{...}: {
  homebrew = {
    enable = true;

    onActivation = {
      autoUpdate = false;
      upgrade = false;
      cleanup = "none";
    };

    taps = [
      "daytonaio/tap"
      "getcompanion-ai/tap"
      "hashicorp/tap"
      "homebrew/services"
      "humanlayer/humanlayer"
      "jnsahaj/lumen"
      "nicosuave/tap"
      "nikitabobko/tap"
      "opencode-ai/tap"
      "pantsbuild/tap"
      "pipedreamhq/pd-cli"
      "steipete/tap"
      "stripe/stripe-cli"
      "supabase/tap"
      "tallesborges/zdx"
      "withgraphite/tap"
    ];

    brews = [
      "apache-arrow"
      "binwalk"
      "cloc"
      "cloudflared"
      "cmake"
      "coreutils"
      "criterion"
      "daytonaio/tap/daytona"
      "diff-so-fancy"
      "e2fsprogs"
      "fd"
      "ffmpeg"
      "flyctl"
      "fzf"
      "gh"
      "git-delta"
      "git-filter-repo"
      "git-lfs"
      "gitleaks"
      "gnu-time"
      "go"
      "hashicorp/tap/terraform"
      "helm"
      "imagemagick"
      "jnsahaj/lumen/lumen"
      "jq"
      "k9s"
      "kind"
      "lazygit"
      "libpq"
      "librsvg"
      "livekit"
      "livekit-cli"
      "llmfit"
      "mactop"
      "minikube"
      "mint"
      "mise"
      "neovim"
      "nicosuave/tap/memex"
      "node"
      "openjdk"
      "pandoc"
      "pipx"
      "poppler"
      "portaudio"
      "postgresql@14"
      "postgresql@16"
      "postgresql@17"
      "potrace"
      "redis"
      "resvg"
      "ripgrep"
      "semgrep"
      "sevenzip"
      "sox"
      "steipete/tap/bird"
      "steipete/tap/gogcli"
      "steipete/tap/summarize"
      "stow"
      "stripe/stripe-cli/stripe"
      "supabase/tap/supabase"
      "swiftformat"
      "swiftlint"
      "tailscale"
      "tmux"
      "tree"
      "trivy"
      "universal-ctags"
      "websocat"
      "wget"
      "withgraphite/tap/graphite"
      "worktrunk"
      "yazi"
      "yq"
      "yt-dlp"
      "zoxide"
      "zsh-autosuggestions"
      "zsh-syntax-highlighting"
    ];

    casks = [
      "aerospace"
      "anaconda"
      "codelayer"
      "codex"
      "codexbar"
      "companion"
      "emacs-app"
      "font-jetbrains-mono"
      "font-symbols-only-nerd-font"
      "gcloud-cli"
      "ghostty@tip"
      "ngrok"
      "opencode-desktop"
      "osaurus"
      "pants"
      "riptide-beta"
      "riptide-dev"
      "riptide-experimental"
      "virtualbox"
      "warp"
    ];
  };
}
