# Lint gates as flake checks.
#
# Every linter the devshell ships also runs as a derivation here, so
# `nix flake check` covers lint locally and in CI with one entrypoint and
# the two can never drift. Each check lints the flake source store path
# read-only and writes an empty $out on success.
#
# hosts/spark/hardware-configuration.nix is excluded from deadnix: it is
# generated by nixos-generate-config and should stay byte-identical to a
# future regeneration, unused module args and all.
{ self, ... }:
{
  perSystem =
    { pkgs, ... }:
    let
      lint =
        name: tools: script:
        pkgs.runCommand "lint-${name}" { nativeBuildInputs = tools; } ''
          cd ${self}
          ${script}
          touch $out
        '';
    in
    {
      checks = {
        statix = lint "statix" [ pkgs.statix ] "statix check .";
        deadnix = lint "deadnix" [ pkgs.deadnix ] ''
          deadnix --fail --exclude ./hosts/spark/hardware-configuration.nix -- .
        '';
        # -i 2 matches the repo's two-space shell style; shfmt walks the
        # directories itself and only considers *.sh and shebanged files.
        shfmt = lint "shfmt" [ pkgs.shfmt ] "shfmt -i 2 -d scripts dots";
        # Config lives in dots/nvim/.stylua.toml; stylua discovers it upward
        # from each file.
        stylua = lint "stylua" [ pkgs.stylua ] "stylua --check dots/nvim";
      };
    };
}
