# Lint gates as flake checks.
#
# Every linter the devshell ships also runs as a derivation here, so
# `nix flake check` covers lint locally and in CI with one entrypoint and
# the two can never drift. Each check lints the flake source store path
# read-only and writes an empty $out on success.
#
# hosts/spark/hardware-configuration.nix is excluded from deadnix: it is
# generated by nixos-generate-config and should stay byte-identical to a
# future regeneration, unused module args and all.
{ self, ... }:
{
  perSystem =
    { pkgs, ... }:
    let
      lint =
        name: tools: script:
        pkgs.runCommand "lint-${name}" { nativeBuildInputs = tools; } ''
          cd ${self}
          ${script}
          touch $out
        '';
    in
    {
      checks = {
        # House nix rules (sgconfig.yml / ast-grep/nix/rules). --error promotes
        # warning-severity rules to gate failures. The companion test check
        # proves every rule still flags its invalid fixtures and passes its
        # valid ones, so a broken rule cannot silently stop matching.
        ast-grep = lint "ast-grep" [ pkgs.ast-grep ] "ast-grep scan --error .";
        ast-grep-test = lint "ast-grep-test" [ pkgs.ast-grep ] "ast-grep test --skip-snapshot-tests";
        statix = lint "statix" [ pkgs.statix ] "statix check .";
        deadnix = lint "deadnix" [ pkgs.deadnix ] ''
          deadnix --fail --exclude ./hosts/spark/hardware-configuration.nix -- .
        '';
        # -i 2 matches the repo's two-space shell style; shfmt walks the
        # directories itself and only considers *.sh and shebanged files.
        # dots/zsh is excluded: shfmt cannot parse zsh syntax (the zsh
        # dotfiles live there since the home-manager removal).
        shfmt = lint "shfmt" [
          pkgs.shfmt
          pkgs.findutils
        ] "shfmt -i 2 -d scripts $(find dots -mindepth 1 -maxdepth 1 ! -name zsh)";
        # Config lives in dots/nvim/.stylua.toml; stylua discovers it upward
        # from each file.
        stylua = lint "stylua" [ pkgs.stylua ] "stylua --check dots/nvim";
      };
    };
}
